### ISSUE TITLE
Chore : 개발 환경 셋팅 및 프로젝트 생성

### ISSUE THREAD

**Issue by Woo-Dong93** [boostcamp-2020/IssueTracker-26#2]
1. 개발 환경 셋팅
- Front_End
- Back_End

2. 프로젝트 생성

**Comment by YiSoJeong** [comment]
## Bug
일부 캠퍼의 로컬에서 기존에 export한 sql문이 적용되지 않음
### 원인
로컬의 MySQL 버전이 낮아 최신 문법을 적용할 수 없었음
### 해결방법
가장 최신의 버전으로 팀원들 로컬 버전 통일 (v 8.x)

**Comment by chahtk** [comment]
### 이슈 발생 상황
`dev branch` 에서 `master branch` 로 checkout 할 때, 분명 ignore 되어 있던 node_modules이 change에 나타났다.
<br>

### 원인
- `master branch` 는 clone 할 때의 상태여서 readme, licence 같은 것 밖에 없었다.
- dev의 `node_modules`는 ignore 되었기 때문에 git에서 관리되지 않는다.
- 따라서 master branch에서는 node_modules이 working directory에 추가된 걸로 판단한 것 같다.

### 해결 방법
- git pull 로 origin의 master를 가져오고 vscode를 껐다 킴.
- gitignore를 수동으로 추가해도 될듯
